export const LIST_CNODE_REQUEST_BEGIN = 'LIST_CNODE_REQUEST_BEGIN'
export const LIST_CNODE_REQUEST_FAILURE = 'LIST_CNODE_REQUEST_FAILURE'
export const LIST_CNODE_REQUEST_SUCCESS = 'LIST_CNODE_REQUEST_SUCCESS'
export const LIST_CNODE_RESOURCE_INIT = 'LIST_CNODE_RESOURCE_INIT'

export const SHOW_CNODE_REQUEST_BEGIN = 'SHOW_CNODE_REQUEST_BEGIN'
export const SHOW_CNODE_REQUEST_FAILURE = 'SHOW_CNODE_REQUEST_FAILURE'
export const SHOW_CNODE_REQUEST_SUCCESS = 'SHOW_CNODE_REQUEST_SUCCESS'
